version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vivat7on/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/

  frontend:
    env_file: .env
    image: vivat7on/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: vivat7on/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 9000:80
