name: Main Kittygram workflow

on:
  push:
    branches:
      - main
      - "*"


jobs:
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Get commit info
        id: commit_info
        run: |
          echo "::set-output name=commit_hash::$(git rev-parse --short ${{ github.sha }})"
          echo "::set-output name=author_name::$(git log -1 --pretty=format:'%an' ${{ github.sha }})"

      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Деплой kittygram успешно выполнен!
            Хеш коммита: ${{ steps.commit_info.outputs.commit_hash }}
            Имя автора: ${{ steps.commit_info.outputs.author_name }}
