name: Main Kittygram workflow

on:
  push:
    branches:
      - main
      - "*"


jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get commit info
        id: commit_info
        run: |
          commit_hash=$(git rev-parse --short ${{ github.sha }})
          author_name=$(git log -1 --pretty=format:'%an' ${{ github.sha }})
          echo "::set-output name=commit_hash::$commit_hash"
          echo "::set-output name=author_name::$author_name"
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ steps.commit_info.outputs.author_name }} успешно задеплоил kittygram!
            Хеш коммита: ${{ steps.commit_info.outputs.commit_hash }}
